services:
  # -------------------
  # ğŸ“¦ Application Service
  # -------------------
  mariadb:
    image: mariadb:10.11
    container_name: chat-db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: admin
      MARIADB_DATABASE: chatdb
      MARIADB_USER: chat_user
      MARIADB_PASSWORD: chat_pwd
      TZ: 'Asia/Seoul'
    volumes:
      - mariadb_data_3307:/var/lib/mysql
    ports:
      - "3307:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  # -------------------
  # ğŸ“Š Monitoring Stack
  # -------------------
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    # mysqld-exporterê°€ ë¨¼ì € ì‹¤í–‰ëœ í›„ prometheusê°€ ì‹¤í–‰ë˜ë„ë¡ ì˜ì¡´ì„± ì¶”ê°€
    depends_on:
      - mysqld-exporter

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus

  mysqld-exporter:
    image: prom/mysqld-exporter:latest
    container_name: mysqld-exporter
    restart: always
    volumes:
      - ./exporter.cnf:/home/.my.cnf
    command:
      - --config.my-cnf=/home/.my.cnf
      - --web.listen-address=:9104
      - --exporter.lock_wait_timeout=5
      - --log.level=info
      - --exporter.log_slow_filter
      - --collect.info_schema.tables.databases=*
    ports:
      - "9104:9104"
    # mariadbê°€ ë¨¼ì € ì‹¤í–‰ëœ í›„ mysqld-exporterê°€ ì‹¤í–‰ë˜ë„ë¡ ì˜ì¡´ì„± ì¶”ê°€
    depends_on:
      - mariadb

# -------------------
# ğŸ’¾ Volumes
# -------------------
volumes:
  mariadb_data_3307: # mariadb ì„œë¹„ìŠ¤ì—ì„œ ì‚¬ìš©í•˜ëŠ” ë³¼ë¥¨
  grafana-data:      # grafana ì„œë¹„ìŠ¤ì—ì„œ ì‚¬ìš©í•˜ëŠ” ë³¼ë¥¨